export const ActionTypes = {
    SET_SERVICES: "SET_SERVICES",
    SELECTED_SERVICES: "SELECTED_SERVICES",
    SET_WORKER: "SET_WORKER",
    SELECTED_WORKER: "SELECTED_WORKER",
    ADD_REQUEST: "ADD_REQUEST",
    CONFIRM_REQUEST: "CONFIRM_REQUEST",
    CANCEL_REQUEST: "CANCEL_REQUEST"
}