CREATE TABLE CUSTOMERS(
	CUSTOMER_ID INT AUTO_INCREMENT,
    USERNAME VARCHAR(15) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    FIRST_NAME VARCHAR(15),
    LAST_NAME VARCHAR(15),
    DOB DATE,
    PHONE VARCHAR(11) UNIQUE,
    CNIC VARCHAR(13) UNIQUE,
    ADDRESS VARCHAR(100),
    
	check(password regexp '[0-9]' and password regexp '[A-Z]' and password regexp '[!@#$%^&*()-_+=.,;:\'"`~]' and length(password) >= 8),
    CHECK(EMAIL REGEXP '^[a-z0-9!#$%&\'*+/=?^_`{|}~-]+(\.[a-z0-9!#$%&\'*+/=?^_`{|}~-]+)*@([a-z0-9]+[a-z0-9-]*)*[a-z0-9]+(\.([a-z0-9]+[a-z0-9-]*)*[a-z0-9]+)*\.[a-z]{2,6}$' and email like '%.com'),
    CHECK(CNIC REGEXP '[0-9]{5,}-[0-9]{7,}-[0-9]'),
    CHECK(PHONE REGEXP '[0-9]{11,}'),
    CHECK(LENGTH(ADDRESS) >= 10),
    CHECK(LENGTH(USERNAME) >=6 AND LENGTH(USERNAME) <= 15),
    CHECK(FIRST_NAME REGEXP '[a-z]{2,15}'),
    CHECK(LAST_NAME REGEXP '[a-z]{2,15}'),
	CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE WORKERS(
	WORKER_ID INT AUTO_INCREMENT,
    FIRST_NAME VARCHAR(15) NOT NULL,
    LAST_NAME VARCHAR(15) NOT NULL,
    PHONE VARCHAR(11) NOT NULL,
    DOB DATE NOT NULL,
    CNIC VARCHAR(15) NOT NULL UNIQUE,
    ADDRESS VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(50),
    AVAILABLE BOOLEAN,
    RATING INT,
    
    CHECK(FIRST_NAME REGEXP '[a-z]{2,15}'),
    CHECK(LAST_NAME REGEXP '[a-z]{2,15}'),
	CHECK(PHONE REGEXP '[0-9]{11,}'),
    CHECK(LENGTH(ADDRESS) >= 10),
    CHECK(EMAIL REGEXP '^[a-z0-9!#$%&\'*+/=?^_`{|}~-]+(\.[a-z0-9!#$%&\'*+/=?^_`{|}~-]+)*@([a-z0-9]+[a-z0-9-]*)*[a-z0-9]+(\.([a-z0-9]+[a-z0-9-]*)*[a-z0-9]+)*\.[a-z]{2,6}$' and email like '%.com'),
	CHECK(CNIC REGEXP '[0-9]{5,}-[0-9]{7,}-[0-9]'),
    
    CONSTRAINT PK_WORKER PRIMARY KEY (WORKER_ID)
);


CREATE TABLE ADMINS(
	id INT AUTO_INCREMENT,
    USERNAME VARCHAR(15) NOT NULL UNIQUE,
    PASSWORD VARCHAR(15) NOT NULL,
    
	CHECK(LENGTH(USERNAME) >=6 AND LENGTH(USERNAME) <= 15),
	check(password regexp '[0-9]' and password regexp '[A-Z]' and password regexp '[!@#$%^&*()-_+=.,;:\'"`~]' and length(password) >= 8),
    CONSTRAINT PK_ADMIN PRIMARY KEY (id)
);

-- CREATE TABLE REQUESTS(
-- 	REQUEST_ID INT AUTO_INCREMENT,
--     CUSTOMER_ID INT,
--     DATE_TIME TIMESTAMP NOT NULL,
--     REQUEST_STATUS VARCHAR(15) NOT NULL,
--     
--     CHECK(LOWER(REQUEST_STATUS) LIKE 'pending' OR LOWER(REQUEST_STATUS) LIKE 'reviewed' OR LOWER(REQUEST_STATUS) LIKE 'approved' OR LOWER(REQUEST_STATUS) LIKE 'rejected' OR LOWER(REQUEST_STATUS) LIKE 'completed'),
--     
--     CONSTRAINT PK_REQUEST PRIMARY KEY (REQUEST_ID),
--     CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
-- );

CREATE TABLE SERVICE_DETAILS(
	SERVICE_DETAIL_ID INT AUTO_INCREMENT,
    WORKER_ID INT,
    SERVICE_ID INT NOT NULL,
    SERVICE_CHARGES FLOAT NOT NULL,
    
    CHECK(SERVICE_CHARGES > 0),
    
    CONSTRAINT PK_SERVICE_DETAIL PRIMARY KEY (SERVICE_DETAIL_ID),
    CONSTRAINT FK_SERVICE_DETAIL_WORKER FOREIGN KEY (WORKER_ID) REFERENCES WORKERS(WORKER_ID),
    CONSTRAINT UNIQUE_WORKER_SERVICE UNIQUE(WORKER_ID, SERVICE_ID),
    CONSTRAINT FK_SERVICE_DETAIL_SERVICE FOREIGN KEY  (SERVICE_ID) REFERENCES SERVICES(SERVICE_ID)
);
select * from jobs;
CREATE TABLE SERVICES(
	SERVICE_ID INT AUTO_INCREMENT,
    SERVICE_TITLE VARCHAR(20) NOT NULL UNIQUE,
    SERVICE_DESCRIPTION VARCHAR(200),
    SERVICE_IMAGE VARCHAR(500),
    SERVICE_RATE FLOAT,
    
    CONSTRAINT PK_SERVICE PRIMARY KEY (SERVICE_ID)
);

CREATE TABLE JOBS(
	JOB_ID INT AUTO_INCREMENT,
    CUSTOMER_ID INT NOT NULL,
    SERVICE_DETAIL_ID INT NOT NULL,
    DATE_TIME TIMESTAMP NOT NULL,
    PAYMENT_METHOD VARCHAR(15),
    JOB_STATUS VARCHAR(15) NOT NULL,
    
    CONSTRAINT PK_SERVICE PRIMARY KEY (JOB_ID),
    CONSTRAINT FK_SERVICE_SERVICE_DETAIL FOREIGN KEY (SERVICE_DETAIL_ID) REFERENCES SERVICE_DETAILS(SERVICE_DETAIL_ID)
);

SELECT * FROM SERVICE_DETAILS;

select * from jobs;

CREATE TABLE REVIEWS(
	REVIEW_ID INT AUTO_INCREMENT,
    JOB_ID INT UNIQUE,
    RATING INT NOT NULL,
    FEEDBACK TEXT,
    
    CHECK(RATING >= 1 AND RATING <= 5),
    CHECK(LENGTH(FEEDBACK) >= 10),
    CONSTRAINT PK_REVIEW PRIMARY KEY (REVIEW_ID),
    CONSTRAINT FK_REVIEW_SERVICE FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID)
);


CREATE TABLE CARD_DETAILS(
	CARD_ID INT AUTO_INCREMENT,
    CUSTOMER_ID INT,
    MM VARCHAR(2),
    YYYY VARCHAR(4),
    CARD_NUM VARCHAR(4),  -- LAST 4 DIGITS
    CVC VARCHAR(4),
    
    CONSTRAINT PK_CARD_DETAILS PRIMARY KEY (CARD_ID),
    CONSTRAINT FK_CARD_DETAILS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

SELECT * FROM REVIEWS;
TRUNCATE TABLE REVIEWS;


