export const ActionTypes = {
    SET_SERVICES: "SET_SERVICES",
    SELECTED_SERVICES: "SELECTED_SERVICES",
    SET_WORKER: "SET_WORKER",
    SELECTED_WORKER: "SELECTED_WORKER",
    REMOVE_WORKER: "REMOVE_WORKER",
    REMOVE_WORKERS: "REMOVE_WORKERS",
    ADD_REQUEST: "ADD_REQUEST",
    CONFIRM_REQUEST: "CONFIRM_REQUEST",
    CANCEL_REQUEST: "CANCEL_REQUEST",
    SET_USER: "SET_USER"
}